  > [4mUnformatted Error Output:[0m
  > File "tests/type_AppliedTooMany/type_AppliedTooMany_3.ml", line 11, characters 5-30:
  > Error: The function applied to this argument has type
  >          customLogOutputProcessors:(string -> string) list ->
  >          customErrorParsers:(string * string list) list -> unit
  > This argument cannot be applied with label ~raiseExceptionDuringParse

[1m[31mError:[0m [4m[36mtests/type_AppliedTooMany/type_AppliedTooMany_3.ml:11 5-30[0m [1m[31m[0m
 8 Â¦ let _ =
 9 Â¦   parseFromStdin
10 Â¦     ~refmttypePath
11 Â¦     ~[4m[1m[31mraiseExceptionDuringParse[0m=true
12 Â¦     ~customLogOutputProcessors=[]
13 Â¦     ~customErrorParsers:[]

The function has type (
  ~customLogOutputProcessors: list(string => string),
  ~customErrorParsers: list((string, list(string)))
) =>
unit

This function doesn't accept an argument named ~raiseExceptionDuringParse.


